import fetch from 'node-fetch';

import { Handler, HandlerEvent } from '@netlify/functions';
import sgMail, { MailDataRequired } from '@sendgrid/mail';

interface EmailParams {
	to: string;
	from: string;
	name: string;
	link: string;
	phone?: string;
	message?: string;
}

interface EmailProps {
	data: EmailParams;
}

interface ResponseInterface {
	statusCode: number;
	body: string;
}

const apiKey = process.env.SENDGRID_API_KEY as string;
if (!apiKey) {
	console.error('SendGrid API key is not set');
	throw new Error('SendGrid API key is not set');
}
sgMail.setApiKey(apiKey);

function extractUsername(email: string): string {
	return email.split('@')[0];
}

export const handler: Handler = async (event: HandlerEvent): Promise<ResponseInterface> => {
	try {
		const { data }: EmailProps = JSON.parse(event.body || '{}');
		const { to, from, name, link, phone, message } = data;

		const response = await fetch(link);
		const arrayBuffer = await response.arrayBuffer();
		const base64Content = Buffer.from(arrayBuffer).toString('base64');

		const mail: MailDataRequired = {
			to,
			from: { email: from, name },
			subject: `${name} - Resume`,
			html: `<p>Hi ${extractUsername(to)},
			</p>
				<p>${message ? message : 'Please find my resume attached with this mail.'}</p>
				<p>Best regards,
					<br>${name}
					${phone ? `<br>${phone}` : ''}
				</p>
				<p>This email was automatically generated by ${name}'s Portfolio. You can still reply to this email for further communication.</p>`,
			attachments: [
				{
					content: base64Content,
					filename: `${name} - Resume.pdf`,
					type: 'application/pdf',
					disposition: 'attachment',
				},
			],
		};

		await sgMail.send(mail);
		return {
			statusCode: 200,
			body: JSON.stringify({ message: 'Email sent successfully' }),
		};
	} catch (error) {
		console.error(error);
		return {
			statusCode: 500,
			body: JSON.stringify({ message: `Error: ${error.message}` }),
		};
	}
};
