import { library } from '@fortawesome/fontawesome-svg-core';
import { faGithub, faLinkedin } from '@fortawesome/free-brands-svg-icons';
import { faSquare } from '@fortawesome/free-regular-svg-icons';
import {
	faAdjust,
	faAngleDown,
	faAngleLeft,
	faAngleRight,
	faArrowDown,
	faArrowUp,
	faArrowUpRightFromSquare,
	faBars,
	faComputer,
	faDatabase,
	faDesktop,
	faEnvelope,
	faGear,
	faGlobe,
	faMoon,
	faNetworkWired,
	faPhone,
	faSearch,
	faServer,
	faSun,
	faTerminal,
} from '@fortawesome/free-solid-svg-icons';

library.add(
	faEnvelope,
	faLinkedin,
	faGithub,
	faSun,
	faMoon,
	faArrowDown,
	faArrowUp,
	faAngleDown,
	faPhone,
	faSearch,
	faBars,
	faAdjust,
	faGear,
	faAngleLeft,
	faAngleRight,
	faArrowUpRightFromSquare,
	faSquare,
	faComputer,
	faServer,
	faNetworkWired,
	faDesktop,
	faTerminal,
	faDatabase,
	faGlobe,
);
