name: Build and Deploy React App

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Install Firebase CLI
              run: npm install -g firebase-tools

            - name: Check Firebase CLI Version
              run: firebase --version

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20.9.0'

            - name: Install dependencies
              run: npm install

            - name: Build the project
              run: npm run build

            - name: Deploy to Preview Channel
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
              run: |
                  npm install -g firebase-tools
                  firebase hosting:channel:deploy preview-channel --expires 1d

            - name: Promote to Live
              if: github.ref == 'refs/heads/main'
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
              run: |
                  npm install -g firebase-tools
                  firebase hosting:channel:deploy live
